BooklyProject/Controllers/AdminLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BooklyProject.Context;

namespace BooklyProject.Controllers
{
    public class AdminLayoutController : Controller
    {
        BooklyContext context = new BooklyContext();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AdminLayoutNavbar()
        {
            var userName = Session["currentUser"].ToString();

            ViewBag.nameSurname = context.Admins.Where(x=>x.UserName == userName).Select(x=>x.FirstName + " " + x.LastName).FirstOrDefault();

            ViewBag.imageUrl = context.Admins.Where(x => x.UserName == userName).Select(x => x.ImageUrl).FirstOrDefault();

            return PartialView();
        }
    }
}

BooklyProject/Views/AdminLayout/AdminLayoutNavbar.cshtml
<ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><img src="@ViewBag.ImageUrl" style="width:30px;height:30px;border-radius:50%" />@ViewBag.nameSurname </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="/Profile/Index">Profil Ayarları</a></li>           
            <li><a class="dropdown-item" href="/Profile/ChangePassword">Şifre Değişikliği</a></li>
            <li><a class="dropdown-item" href="/Default/Index">Siteye Git</a></li>
            <li><hr class="dropdown-divider" /></li>
            <li><a class="dropdown-item" href="/Login/Logout">Çıkış Yap</a></li>
        </ul>
    </li>
</ul>

BooklyProject/Views/AdminLayout/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Static Navigation - SB Admin</title>
    <link href="~/Templates/sb-admin/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">Admin Paneli</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Ara..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>
        <!-- Navbar-->
        @Html.Action("AdminLayoutNavbar", "AdminLayout")
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="/Dashboard/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <a class="nav-link" href="/Category/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-list"></i></div>
                            Kategoriler
                        </a>
                        <a class="nav-link" href="/Books/Index">
                            <div class="sb-nav-link-icon"><i class="fa fa-book-open"></i></div>
                            Kitaplar
                        </a>
                        <a class="nav-link" href="/Authors/Index">
                            <div class="sb-nav-link-icon"><i class="fa fa-user "></i></div>
                            Yazarlar
                        </a>
                        <a class="nav-link" href="/PhotoGallery/Index">
                            <div class="sb-nav-link-icon"><i class="fa fa-camera "></i></div>
                            Fotoğraf Galerisi
                        </a>
                        <a class="nav-link" href="/Testimonials/Index">
                            <div class="sb-nav-link-icon"><i class="fa fa-user "></i></div>
                            Referanslar
                        </a>
                        <a class="nav-link" href="/Banner/Index">
                            <div class="sb-nav-link-icon"><i class="fa fa-bars "></i></div>
                            Bannerlar
                        </a>
                        <a class="nav-link" href="/Default/Index">
                            <div class="sb-nav-link-icon"><i class="fa fa-search "></i></div>
                            Siteye Git
                        </a>

                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Templates/sb-admin/js/scripts.js"></script>
   
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="~/Templates/sb-admin/assets/demo/chart-area-demo.js"></script>
    <script src="~/Templates/sb-admin/assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
    <script src="~/Templates/sb-admin/js/datatables-simple-demo.js"></script>
</body>
</html>